### ISSUE TITLE
High Brightness and Low Volume Issue 

### ISSUE THREAD

**Issue by RPrrasad** [PixelExperience/android-issues#371]
## Build date
```
PixelExperience_X01BD-11.0-20210717-0745-OFFICIAL.zip
```

## Expected Behavior
```
- Brightness should work normally as before, if possible
- Volume should be equally louder on everything I.e., music, calling etc., sane as stock rom, if possible

```

## Current Behavior
```
- Brightness level need to set 85 above to clear view
- Low volume on everything like Music, calling.

```

## Possible Solution
```
No idea. In the next update if the issue solved that would be great.
```

## Steps to Reproduce

```
1.  Open settings and set brightness to minimum, or set auto brightness and adjust bar to minimum.
2.  Volume set to high
3.
4.
```

/device X01BD
/version eleven

**Comment by Gaurav241** [comment]
Fixed in latest update.

You can close this issue

**Comment by RPrrasad** [comment]
Updated to the latest august update but low volume issue still there. Anyway thanks for the efforts, i hope it resolves in future update
